name = "WormlikeChain"
uuid = "150a60af-03bd-480c-bf88-ed8ebe43ba3c"
authors = ["Nathan Zimmerberg <nhz2@cornell.edu> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
RNGTest = "97cc5700-e6cb-5ca1-8fb2-7f6b45264ecd"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Random123 = "1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
